fail_fast: false
default_stages: [commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: debug-statements
        name: pdb_debug-statements
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      # Run the Ruff formatter.
      - id: ruff-format