[tool.poetry]
name = "pywright"
version = "0.1.0"
description = ""
authors = ["pjfig <pjsfigueira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest-playwright = "^0.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
